Flask/SQLAlchemy/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    name = db.Column(db.Text)
    uid = db.Column(db.Integer, primary_key = True)
    age = db.Column(db.Integer, nullable = True)

    def __repr__(self):
        return f'{self.name}, {self.age}'

Flask/SQLAlchemy/app.py
from models import db
from flask import Flask, Blueprint
from flask_migrate import Migrate
from views import views

def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///./testdb.db'

    db.init_app(app)

    app.register_blueprint(views, url_prefix = '/')

    Migrate(app, db)


    return app

Flask/SQLAlchemy/views.py
from models import db
from flask import Blueprint, request, render_template, jsonify
from models import User

views = Blueprint('views', __name__)

@views.route('/', methods = ['GET', 'POST'])
def get_and_create_users():
    if request.method == 'GET':
        users = User.query.all()
        return render_template('home.html', users = users)
    
    elif request.method == 'POST':
        name = request.form.get('name')
        age = request.form.get('age')
        user = User(name = name, age = int(age))

        db.session.add(user)
        db.session.commit()
        users = User.query.all()
        return render_template('home.html', users = users)
        

@views.route('/delete/<pid>', methods = ['DELETE'])
def delete(pid):
    user = User.query.get(pid)
    if not user:
        return jsonify({
            "error" : "User not found"
        })
    db.session.delete(user)
    db.session.commit()
    users = User.query.all()
    return render_template('home.html', users = users)


@views.route('/details/<pid>', methods = ['GET'])
def details(pid):
    user = User.query.get(pid)
    if not user:
        return jsonify({
            "error" : "User not found"
        })
    return render_template('details.html', user = user)

@views.route('/update/<int:pid>', methods = ['GET', 'PUT'])
def update(pid):
    if request.method == 'PUT':
        user = User.query.get(pid)
        if not user:
            return jsonify({
                "error" : "User not found"
            })
        data = request.get_json()
        name = data.get('name', user.name)
        age = data.get('age', user.age)

        if name is not '':
            user.name = name

        if age is not '':
            user.age = age

        db.session.commit()
        return jsonify({"message": "User updated successfully"}), 200
    elif request.method == 'GET':
        user = User.query.get(pid)
        return render_template('update.html', user = user)

Flask/SQLAlchemy/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test DB</title>
</head>
<body>
    {% block content %}
        
    {% endblock %}
</body>
</html>

Flask/SQLAlchemy/templates/details.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ user.name }}</h1>
{% endblock  %}

Flask/SQLAlchemy/templates/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Home Page</h1>
    <ul>
        {% for user in users %}
        <li>{{ user }} <button onclick="deleteUser({{ user.uid }})">Delete</button>
        <a href="{{ url_for('views.details', pid = user.uid) }}"> Details</a>
        <button onclick="redirectToUpdate({{ user.uid }})">Update</button>

        </li>
        {% endfor %}
    </ul>

    <h2>Create new user</h2>
    <form action="{{ url_for('views.get_and_create_users')}}" method="post">
        <input type="text" name="name" placeholder = 'Your Name' required>
        <input type="number" name="age" placeholder = 'Your age'>
        <input type="submit" value="Create">
    </form>

    <script>
        async function deleteUser(uid)
        {
            const url = `/delete/${uid}`;
            options = {
                method : 'DELETE'
            };
            try
            {
            const response = await fetch(url, options);
            if(response.ok) {
                alert('User deteled successfully');
                location.reload();
            }
            else {
                alert('User not deteled successfully');
            }
        } catch(error) {
            alert("Error")
            console.error(error)
        }
        }
            function redirectToUpdate(uid) {
                const url = `/update/${uid}`; // Construct the URL dynamically
                window.location.href = url;  // Redirect the browser to the update page
            }
        
        
    </script>
{% endblock  %}

Flask/SQLAlchemy/templates/update.html
{% extends "base.html" %}

{% block content %}
<form action="{{url_for('views.update', pid = user.uid)}}" method="post">
    <input type="text" id="name" name = "name" placeholder="{{user.name}}">
    <input type="number" id="age" name = "age" placeholder="{{user.age}}">
    <button type="button" onclick = "updateUser({{user.uid}})">Update</button>
</form>

<script>
    async function updateUser(uid)
    {
        const url = `/update/${uid}`;
        const data = {
            name : document.getElementById("name").value,
            age : document.getElementById("age").value
        };

        const options = {
            method : 'PUT',
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(data)
        }

        const response = await fetch(url, options)
        if (response.ok) {
            window.location.href = "/";
        }

    }

</script>
{% endblock  %}