Django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.welcomePage, name="welcome_page"),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django/mysite/posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.homePage, name="homepage"),
    path('new-post', views.new_post, name="new-post"),
    path('<slug:id>', views.post_page, name = "page")
]

Django/mysite/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

Django/mysite/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    slug = models.SlugField()
    published_date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default="None", blank=True, null=True)

    def __str__(self) -> str:
        return self.title

Django/mysite/users/models.py
from django.db import models

# Create your models here.

class user(models.Model):
    username = models.CharField(max_length=75)
    password = models.CharField(max_length=75)

    def __str__(self) -> str:
        return self.username

Django/mysite/posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'content', 'slug', 'banner']

Django/mysite/mysite/views.py
from django.shortcuts import render

def welcomePage(request):
    return render(request, 'welcome_page.html')

Django/mysite/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms
def homePage(request):
    posts = Post.objects.all().order_by('-published_date')
    return render(request, 'posts/homepage.html', { 'posts' : posts})


def post_page(request, id):
    post = Post.objects.get(slug = id)
    return render(request, 'posts/post_page.html', {'post' : post})

@login_required(login_url="/users/login/")
def new_post(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            return redirect("posts:homepage")
    else:
        form = forms.CreatePost()
    return render(request, "posts/new_post.html", {'form':form})

Django/mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:homepage")
        else:
            return render(request, "users/register_page.html", { "form": form })
    else:
        form = UserCreationForm()
    return render(request, 'users/register_page.html', {"form" : form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:homepage")
    else:
        form = AuthenticationForm()
    return render(request, "users/login_page.html", {"form": form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:homepage")
        

Django/mysite/posts/templates/posts/homepage.html
{% extends "layout.html" %} 
{% block heading %} 
    Posts Home Page 
{% endblock %}
{% block content %}
    <section>
        <h1>Posts</h1>
        <article class = "post">
            {% for post in posts %}
                <h2><a href="{% url 'posts:page' id=post.slug %}">{{ post.title }}</a></h2>
                <p>{{ post.published_date }}</p>
                <p>{{ post.content }}</p>
            {% endfor %}
        </article>
    </section>
{% endblock %}

Django/mysite/posts/templates/posts/new_post.html
{% extends "layout.html" %}

{% block heading %}
New Post
{% endblock  %}
{% block content %}
    <h1>New Post</h1>
    <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit" type="submit"></button>
    </form>
{% endblock  %}

Django/mysite/posts/templates/posts/post_page.html
{% extends "layout.html" %}
{% block heading %}
{% endblock  %}

{% block content %}
    <img class="banner" src="{{ post.banner.url }}" alt="{{ post.title }}"/>    
    <h1>{{ post.title }}</h1>
    <p>{{ post.published_date }}</p>
    <p>{{ post.content }}</p>
{% endblock  %}

Django/mysite/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>
        {% block heading %} Django app{% endblock %}
    </title>
  </head>
  <body>
    <nav>
      <a href="{% url 'welcome_page' %}"><span title="Home" aria-label="Home" role="img">🏠</span></a> |
      <a href="{% url 'posts:homepage' %}">📰</a> |
      {% if not user.is_authenticated %}
        <a href="{% url 'users:register' %}">Register</a> |
        <a href="{% url 'users:login' %}"><span title="Login" aria-label="Login" role="img">🔏</span>
      {% else %}
        <form action="{% url 'users:logout' %}" method="post">
          {% csrf_token %}
          <button type="submit" title="Log out" aria-label="Log out">👋</button>
        </form>
        </a> |
        <a href="{% url 'posts:new-post' %}"><span title="New post" aria-label="New Post" role="img">🆕</span></a>
      {% endif %}
    </nav>
    <main>
        {% block content %}{% endblock %}
    </main>
  </body>
</html>

Django/mysite/templates/welcome_page.html
{% extends "layout.html" %} 
{% block heading %} 
    Welcome 
{% endblock %}

{% block content %}
    <h1>Welcome Page</h1>
    <p>Check out my <a href="{% url 'posts:homepage' %}">Home</a> page.</p>
{% endblock %}

Django/mysite/users/templates/users/login_page.html
{% extends "layout.html" %}

{% block heading %}
User Login
{% endblock  %}

{% block content %}
<h1>User Login</h1>
<form class="form-with-validation" action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}"/>
    {% endif %}
    <button class="form-submit" type="submit">Submit</button>
</form>
{% endblock  %}

Django/mysite/users/templates/users/register_page.html
{% extends "layout.html" %}
{% block heading %}
    Register
{% endblock  %}
{% block content %}
    <form class="form-with-validation" action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit" type="submit">Submit</button>
    </form>
{% endblock  %}